"use client";

import Link from "next/link";
import { ArrowRight, Compass } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { HeroVisual } from "./HeroVisual";

export function Hero() {
  const facts = [{ value: "8", unit: "GETs", label: "Data Routes" }, { value: "3", unit: "Layers", label: "Map Endpoints" }, { value: "0", unit: "Fake", label: "Fallback Values" }];
  return <section className="relative overflow-hidden bg-grid-pattern pb-20 pt-32 md:pb-28 md:pt-40"><div className="absolute left-1/2 top-1/4 h-[350px] w-[600px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-gradient-to-tr from-cyan-500/10 via-blue-600/10 to-indigo-900/10 blur-3xl" /><div className="relative z-10 mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid items-center gap-12 lg:grid-cols-12"><div className="space-y-6 text-center lg:col-span-6 lg:text-left"><div className="inline-flex items-center gap-2 rounded-full border border-cyan-500/30 bg-slate-900/90 px-3 py-1.5 text-xs font-mono text-cyan-300"><span className="h-2 w-2 rounded-full bg-cyan-400" />EARTH OBSERVATION AND URBAN DATA</div><h1 className="text-4xl font-extrabold leading-[1.1] text-white sm:text-5xl lg:text-6xl">Understand Your City. <span className="bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">Shape Its Future.</span></h1><p className="mx-auto max-w-xl text-base leading-relaxed text-slate-300 lg:mx-0">Aetherion CityIntel presents the environmental, geographic, and population records supplied by the project backend.</p><div className="flex flex-col items-center justify-center gap-4 pt-2 sm:flex-row lg:justify-start"><Link href="/explore"><Button variant="glow" size="lg" rightIcon={<ArrowRight className="h-4 w-4" />}>Explore Aetherion CityIntel</Button></Link><a href="#how-it-works"><Button variant="secondary" size="lg" leftIcon={<Compass className="h-4 w-4 text-cyan-400" />}>See How It Works</Button></a></div><div className="grid grid-cols-3 gap-4 border-t border-slate-800/80 pt-6 text-left">{facts.map((fact) => <div key={fact.label}><div className="flex items-baseline gap-1 text-xl font-bold font-mono text-white">{fact.value}<span className="text-xs font-normal text-cyan-400">{fact.unit}</span></div><div className="text-[11px] font-mono uppercase tracking-wider text-slate-400">{fact.label}</div></div>)}</div></div><div className="flex items-center justify-center lg:col-span-6"><HeroVisual /></div></div></div></section>;
}
